---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian9
  - distro: debian8
  - distro: ubuntu1804
  - distro: ubuntu1604
  - distro: ubuntu1404


script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure PHP is installable and at the right version.
  - 'docker exec --tty ${container_id} env TERM=xterm apt-cache search php*-fpm'
  - 'docker exec --tty ${container_id} env TERM=xterm apt-cache search php*-fpm | grep php7.0-fpm'
  - 'docker exec --tty ${container_id} env TERM=xterm apt-cache search php*-fpm | grep php7.1-fpm'
  - 'docker exec --tty ${container_id} env TERM=xterm apt-cache search php*-fpm | grep php7.2-fpm'

after_failure:
  - docker exec --tty ${container_id} env TERM=xterm apt-cache search php*

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
